# see config.py for details
telegram_token: ""
telegram_usernames: []
telegram_chat_ids: []

openai_api_key: ""
openai_model: "gpt-3.5-turbo"
max_history_depth: 3

persistence_path: "./data/persistence.pkl"

commands:
    bugfix: "Examine the following code. Rewrite it if necessary to fix bugs and various problems. Explain the changes you've made."

    proofread: "Proofread the following text. Correct grammar and punctuation errors. Rephrase if necessary. Make sure the resulting text is clear, concise, and easy to read. Explain the changes you've made."

    summarize: "Explain the following text in simple terms. Use no more than two paragraphs."

    translate: "Translate the following text into English."
