# Bot configuration parameters.

# Telegram Bot API token.
telegram_token: ""

# The list of Telegram usernames allowed to chat with the bot.
# If empty, the bot will be available to anyone.
telegram_usernames: []

# The list of Telegram group ids, whose members are allowed to chat with the bot.
# If empty, the bot will only be available to `telegram_usernames`.
telegram_chat_ids: []

# OpenAI API key.
openai_api_key: ""

# OpenAI model name. One of the following:
# gpt-3.5-turbo | gpt-4
openai_model: "gpt-3.5-turbo"

# The maximum number of previous messages
# the bot will remember when talking to a user.
max_history_depth: 3

# Enable/disable image generation.
imagine: yes

# Where to store the chat context file.
persistence_path: "./data/persistence.pkl"

# Custom AI commands (additional prompts)
shortcuts:
    bugfix: "Examine the following code. Rewrite it if necessary to fix bugs and various problems. Explain the changes you've made."

    proofread: "Proofread the following text. Correct grammar and punctuation errors. Rephrase if necessary. Make sure the resulting text is clear, concise, and easy to read. Explain the changes you've made."

    summarize: "Explain the following text in simple terms. Use no more than two paragraphs."

    translate: "Translate the following text into English."
