# see config.py for details
telegram_token: ""
openai_api_key: ""
openai_model: "gpt-3.5-turbo"
telegram_usernames: []
telegram_chat_ids: []
max_history_depth: 3
persistence_path: "./data/persistence.pkl"
