version: "3"

services:
    pokitoki:
        container_name: pokitoki
        command: python3 -m bot.bot
        restart: always
        build:
            context: "."
            dockerfile: Dockerfile
